[build]
command = "npm run build"
publish = "out"

[dev]
framework = "#static"
publish = "out"
autoLaunch = true

[[redirects]]
from = "/*/edit"
to = "/[project]/edit.html"
status = 200

[[redirects]]
from = "/*"
to = "/[project].html"
status = 200
